tz_42cc/urls.py
from django.conf import settings as django_settings
from django.conf.urls.defaults import *
from django.contrib import admin

from bio.views import index, settings, edit_person, logout_user, loglist

admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', index),
    (r'^edit/$', edit_person),
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_user),
    (r'^settings/$', settings),
    (r'^loglist/$', loglist),
    (r'^site_media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': django_settings.MEDIA_ROOT}),
    (r'^edit/$', edit_person),
    (r'^site_media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': django_settings.MEDIA_ROOT}),
)

tz_42cc/bio/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models
#imports for signal dispatcher
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_init, post_save, post_delete


#That class represents a person
class Person(models.Model):
    name = models.CharField(max_length=255,
                            verbose_name=u'Имя:')
    surname = models.CharField(max_length=255,
                            verbose_name=u'Фамилия:')
    bio = models.TextField(max_length=255,
                            blank=True,
                            verbose_name=u'Биография:')
    contacts = models.CharField(max_length=255,
                            verbose_name=u'Контакты:')
    birthdate = models.DateField(verbose_name=u'Дата рождения:',
                            blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.name, self.surname)


def get_choices():
    result = tuple()
    for i in range(0, 10):
        result += (i, 'Priority %d' % (i + 1)),

    return result


class HttpRequestData(models.Model):

    PRIORITY_CHOICES = get_choices()

    path = models.TextField()
    method = models.CharField(max_length=5)
    request = models.TextField()
    cookies = models.TextField(blank=True)
    meta = models.TextField()
    user = models.TextField(blank=True)
    date = models.DateTimeField(default=datetime.now)
    priority = models.IntegerField(choices=PRIORITY_CHOICES,
                            default=0,
    )

    def __unicode__(self):
        return u'%s %s' % (self.path, self.request, self.priority)


class SignalLog(models.Model):
    souce = models.CharField(max_length=254)
    type = models.CharField(max_length=15)

    def __unicode__(self):
        return u'%s %s' % (self.type, self.souce)


def my_callback(sender, **kwargs):
    if sender == SignalLog:             # don`t log self
        return
    elif sender == ContentType:           # dont fail django test
        return

    try:
        # get signal from kwargs arguments
        signal = kwargs.get('signal')
        # get dispatch_uid if present
        action = signal.__dict__['receivers'][0][0][0]
    except:
        action = 'can`t detect'
    signal_log = SignalLog(souce=str(sender), type=action)
    signal_log.save()

post_init.connect(my_callback, dispatch_uid='init')
post_save.connect(my_callback, dispatch_uid='save')
post_delete.connect(my_callback, dispatch_uid='delete')

tz_42cc/bio/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import BaseValidator
from django.forms import ModelForm, Textarea

from models import Person
from widgets import CalendarWidget


# Create the form class.
class PersonForm(ModelForm):
    birthdate = forms.DateField(widget=CalendarWidget())

    def __init__(self, *args, **kw):
        super(ModelForm, self).__init__(*args, **kw)
        self.fields.keyOrder.reverse()

    def ajax_response(self, sucsess_text=''):
        return u'<div class = "save_result">%s</div><table>%s</table>\
        <input type="submit" value="Редактировать">' % (sucsess_text,
                                                       self.as_table(),)

    class Meta:
        model = Person

tz_42cc/bio/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext

from context_processor import get_settings
from forms import PersonForm
from models import Person, HttpRequestData


def index(request):
    person = Person.objects.all()[0]  # first person in DB
    #get list (verbose_name,value) for object
    person_data = []
    for field in person._meta.fields:
        key = field.verbose_name
        value = person.__getattribute__(field.name)
        if key == 'ID':
            continue
        person_data.append((key, value))

    return render_to_response('bio/index.html',
                        {'person': person_data, 'request': request},
                        context_instance=RequestContext(request))


def settings(request):
    context = RequestContext(request, {}, [get_settings])
    return render_to_response('settings.html', context_instance=context)


@login_required
def edit_person(request):
    first_person = Person.objects.all()[0]  # first person in DB
    form = PersonForm(instance=first_person)
    if request.method == 'POST':  # recived post data to save
        # load post data into object
        form = PersonForm(request.POST, instance=first_person)
        sucsess_text = 'form data not saved'
        if form.is_valid():  # if form data are valid
            form.save()      # save data from object to DB
            sucsess_text = 'data saved'
        return HttpResponse(form.ajax_response(sucsess_text))
    return render_to_response('bio/edit.html',
                              {'form': form},
                              context_instance=RequestContext(request))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')


def loglist(request):
    if 'order' in request.REQUEST:
        order = request.REQUEST['order']
        log_list = HttpRequestData.objects.order_by(order)[:10]
    else:
        log_list = HttpRequestData.objects.all()[:10]
    return render_to_response('log_list.html', {'log_list': log_list},
                              context_instance=RequestContext(request))


def settings(request):
    context = RequestContext(request, {}, [get_settings])
    return render_to_response('settings.html', context_instance=context)


def test_tag(request):
    return render_to_response('test_tag.html',
                              {'request': request},
                              context_instance=RequestContext(request))


def loglist(request):
    if request.method == 'POST':
        record = HttpRequestData.objects.get(pk=request.REQUEST['pk'])
        record.priority = int(request.REQUEST['priority'][9]) - 1
        record.save()
        redirect_to = request.META['HTTP_REFERER'] if \
                        'HTTP_REFERER' in request.META else '/loglist/'
        return HttpResponseRedirect(redirect_to)

    if 'order' in request.REQUEST:
        order = request.REQUEST['order']
        log_list = HttpRequestData.objects.order_by(order)[:10]
    else:
        log_list = HttpRequestData.objects.all()[:10]
    return render_to_response('log_list.html',
                                {
                                 'log_list': log_list,
                                 'range': range(1, 10),
                                },
                                context_instance=RequestContext(request))

tz_42cc/templates/base_generic.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>
        {% block title %}BASE{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="/media/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/media/css/forms.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/project.css" />
    {% block js %} {% endblock %}
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

tz_42cc/templates/bio/edit.html
{% extends "base_generic.html" %}
{% block title %}edit page{% endblock %}
{% block js %} {{ form.media }} {% endblock%}
{% block content %}
<div>
    <h3 class="edit_caption">
    edit person
    </h3>
</div>
<form id="editForm1" action="/edit/" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Редактировать">
</form>
<div id="progress" class="progress_bar">
&nbsp
</div>
{% endblock %}

tz_42cc/templates/bio/index.html
{% extends "base_generic.html" %}
{% block title %}TZ{% endblock %}
{% block content %}
<dl>
{% for key, value in person %}
    <dt>{{ key }}</dt>
    {{ value }}</dd>
{% endfor %}
</dl>
<HR>
<p>links to test task parts:</p>
<ul>
    <li><a href="/settings/">Ticket#4</a></li>
    <li><a href="/edit/">Ticket#5, Ticket#2, Ticket#6, Ticket#7, Ticket#11</a></li>
    <li>Ticket#8 {% load edit_link %}{% edit_link request.user %}</li>
    <li><a href="/loglist/">Ticket#12, Ticket#13</a></li>
    <li><a href="/logout/">Log out</a></li>
</ul>
{% endblock %}

tz_42cc/templates/log_list.html
{% extends "base_generic.html" %}
{% block title %}view logs{% endblock%}
{% block content %}
{% if log_list %}
    <table border='1' width="100%">
        <tr>
            <td>ID</td>
            <td>path</td>
            <td>method</td>
            <td>request</td>
            <td>date</td>
            <td><b> prioroty </b>
            <HR>
            sort optons: <BR>
            <a href='/loglist?order=-priority'> Priority 1 </a> <BR>
            <a href='/loglist?order=priority'> empty </a></td>
            <td><b> change priority </b></td>
         </tr>
        {% for record in log_list %}
         <tr>
            <td>{{ record.pk }}</td>
            <td>{{ record.path }}</td>
            <td>{{ record.method }}</td>
            <td>{{ record.request }}</td>
            <td>{{ record.date }}</td>
            <td>{{ record.get_priority_display }}</td>
            <td>
            <form action='/loglist/' method='POST'>{% csrf_token %}
                <input type="hidden" name='pk' value='{{ record.pk }}'>
                <select name='priority'>
                {% for i in range %}
                    <option>Priority {{ i }}</option>
                {% endfor %}
                </select>
                <input type="submit" value="Редактировать">
            </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>no logs found</p>
{% endif %}
{% endblock %}

tz_42cc/templates/settings.html
{% extends "base_generic.html" %} {% block title %}
template-context-processor {% endblock %} {% block content %} django
settings
<table border=1>
    <tr>
        <td><b> Setting </b></td>
        <td><b> Value </b></td>
    </tr>
    {% for setting, val in settings.items %}
        <tr>
            <td>{{ setting }}</td>
            <td>{{ val }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}